<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content='計数工学科アルゴリズム班によって制作されたアプリケーション、"MaySearch"が、あなたの五月祭ライフをより楽しく快適にします'>
    <meta name="title" content="Yuri Mikawa">

    <title>立替さん</title>

    <link href="/plugin/css/bootstrap.min.css" rel="stylesheet">
    <link href="/plugin/pe-icon-7-stroke/css/pe-icon-7-stroke.css" rel="stylesheet">

</head>
<body>

<div>

    <div>
        <div>

            <div class="row">
                <div class="col-lg-4">
                    <div class="row">
                        <div class="col-lg-12">
                            立替さん
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-2">
                            <div class="row"><div class="col-lg-12">名前</div></div>
                            <?php foreach ($this->memName as $item): ?>
                                <div class="row"><div class="col-lg-12"><?php echo $item; ?></div></div>
                            <?php endforeach; ?>
                        </div>
                        <div class="col-xs-3">
                            <div class="row"><div class="col-lg-12">現在の合計</div></div>
                            <div class="row"><div class="col-lg-12"><?php  ?></div></div>
                        </div>
                    </div>
                </div>

                <a href="/">元のページに戻る</a>

                <div class="col-lg-8">
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Mainly scripts -->
<script src="/plugin/js/jquery-3.1.1.min.js"></script>
<script src="/plugin/js/bootstrap.min.js"></script>
<script src="/plugin/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/plugin/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

<!-- Custom and plugin javascript -->
<script src="/plugin/js/inspinia.js"></script>
<script src="/plugin/js/plugins/pace/pace.min.js"></script>

<!-- Steps -->
<script src="/plugin/js/plugins/steps/jquery.steps.min.js"></script>

<script>

    $('#mem-num').change(function() {
        var num = parseInt($(this).val());
        $("#num").val(num);
        console.log(num);
        $("#mem-name-box").html("");
        for (var i=0; i<num; i++) {
            var inputbox = $("#mem-name").clone();
            $(inputbox).removeAttr("id");
            $(inputbox).removeAttr("style");
            $(inputbox).attr("name", "mem-name" + num);
            $(inputbox).appendTo("#mem-name-box");
        }

    });


    /* twitterシェア*/
    window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));

    $(document).ready(function() {
        $("#form").steps({
            bodyTag: "fieldset",
            labels: {
                finish: "探索開始",
                next: "次へ",
                previous: "戻る"
            },
            enableAllSteps: true,
            onStepChanging: function (event, currentIndex, newIndex) {
                // スムーススクロール
                $('body,html').animate({scrollTop: $('#all-cover').offset().top}, 400, 'swing');

                //if (currentIndex > newIndex) return true;

                if (newIndex == 1 && currentIndex < newIndex) {
                    var res = NoStep1($('input[name="clock1"]').val(), $('input[name="clock2"]').val());
                    if (!res) return false;
                    TimePost1($('input[name="date"]:checked').val());
                }

                if (newIndex == 2 && currentIndex < newIndex) {
                    //時間が更新されたので、予め確認画面の企画を全て消去
                    $('.last-conf').remove();
                    var start_pos = $('input[name="start-pos"]').val();
                    res = NoStep2(start_pos);
                    if (!res) return false;
                    TimePost2($('input[name="date"]:checked').val(), $('input[name="clock1"]').val(), $('input[name="clock2"]').val());
                }

                if (newIndex - currentIndex > 1) return false;

                var form = $(this);

                if (currentIndex < newIndex) {
                    // To remove error styles
                    $(".body:eq(" + newIndex + ") label.error", form).remove();
                    $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                }
                return true;

            },
            onFinishing: function (event, currentIndex) {
                var search = FinishCheck();
                if (search.length == 0) {
                    ErrorMsg("企画が選択されてません", "検索するには、企画を１つ以上選択してください");

                } else if (search.length > 20) {

                    ErrorMsg("企画の数が多すぎます", "検索するには、企画は20個以下にしてください");
                } else {
                    var time = FinishTimeCheck(search);
                    $('#page-wrapper').addClass('sk-loading');
                    var ajaxpost = FinishPost(search, time, $('input[name="start-pos"]').val(), $('input[name="date"]:checked').val(), $('input[name="clock1"]').val(), $('input[name="clock2"]').val());
                    $('#search-stop').click(function () {
                        $('#page-wrapper').removeClass('sk-loading');
                        ajaxpost.abort();
                        return false;
                    });
                    return true;
                }
            }
        });
    });
</script>

<!-- Clock picker -->
<script src="/plugin/js/plugins/clockpicker/clockpicker.js"></script>

<!-- Select2 -->
<!--<script src="/plugin/js/plugins/select2/select2.full.min.js"></script>-->

<!--select2 その２-->
<script src="/js/select2/select2.full.min.js"></script>

<!-- Sweet alert -->
<script src="/plugin/js/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-99122786-1', 'auto');
    ga('send', 'pageview');

    $(document).ready(function() {
        $('head link:last').after('<link rel="stylesheet" href="/plugin/css/plugins/clockpicker/clockpicker.css">');
        RemoveClock(navigator.userAgent);
        //SetNow();

        /*日付変更関連*/
        $('input[name="date"]').change(function() {ChangeDate()});

        $('input[name="no-time"]').change(function() {NoTimeCheck()});

        $('input[name="clock1"]').change(function() {TimeChange(1, $(this).val())});
        $('input[name="clock2"]').change(function() {TimeChange(2, $(this).val())});
        //select2
        var style = '<link rel="stylesheet" href="/plugin/css/plugins/select2/select2.min.css">';
        $('head link:last').after(style);
        //SweerAlert
        style = '<link rel="stylesheet" href="/plugin/css/plugins/sweetalert/sweetalert.css">';
        $('head link:last').after(style);
        $('#toppage-may').hover(function() {
            $('#toppage-comment').fadeIn('fast');
        }, function() {
            $('#toppage-comment').fadeOut('fast');

        });

    });

    function RemoveClock(agent) {
        if (agent.search(/iPhone/) != -1 || agent.search(/iPod/) != -1 || agent.search(/Android/) != -1) { //スマートフォン
            $('#clock-check').remove();
        } else { //PC,タブレット
            $('#time-check').remove();
            //clockpicker
            $('#clock1').clockpicker({
                placement: 'bottom',
                align: 'left',
                autoclose: true,
                'default': '現在時刻'
            });
            $('#clock2').clockpicker({
                placement: 'bottom',
                align: 'left',
                autoclose: true,
            });
        }
    }
    function SetNow() {
        var now = new Date();
        var val;
        var h = now.getHours();
        if(h < 9 || h >= 18){//9時前あるいは18時以降
            val = "09:00";
        } else {
            var m = now.getMinutes();
            h = String(h); m = String(m);
            if (h.length == 1) h = "0" + h;
            if (m.length == 1) m = "0" + m;
            val = h + ":" + m;
        }
        $('#clockText1').text(val);
        $('input[name="clock1"]').attr("value", val).attr('placeholder', val);
    }
    function ChangeDate() {
        if ($('input#1day').is(':checked')) $("#jQueryTime").text('１日目（２０日）');
        else $("#jQueryTime").text('２日目（２１日）');
    }
    function NoTimeCheck() {
        if ($('input[name="no-time"]').is(':checked')) $('#input-clock2').val("18:00").prop("disabled", true);
        else $('#input-clock2').prop("disabled", false);
    }
    function TimeChange(num, time) {
        if (!time) {
            $('#clock-check').addClass('has-error');
            $('#clock-check-help').show();
            return false;
        }
        var time_ = $('input[name="clock' + String(3 - parseInt(num)) + '"]').val();

        var arr = new Array();
        var h, m;
        var flg = 1;
        h = time.substr(0, 2); m = time.substr(3, 2);
        if ($.isNumeric(h) && $.isNumeric(m)) {
            arr[parseInt(num) - 1] = parseInt(h * 60) + parseInt(m);
        } else flg = 0;
        h = time_.substr(0, 2); m = time_.substr(3, 2);
        if ($.isNumeric(h) && $.isNumeric(m)) {
            arr[2 - parseInt(num)] = parseInt(h * 60) + parseInt(m);
        } else flg = 0;
        if ((parseInt(arr[0]) >= parseInt(arr[1]) || parseInt(arr[0]) >= 1080 || parseInt(arr[0]) < 540 || parseInt(arr[1]) <= 540 || parseInt(arr[1]) > 1080)
            && flg == 1) {
            $('#clock-check').addClass('has-error');
            $('#clock-check-help').show();
        } else {
            $('#clockText' + num).text(time);
            $('#clock-check').removeClass('has-error');
            $('#clock-check-help').hide();
        }
    }

    function TimePost1(date) {
        $.ajax({
            url: "/search/time-post1",
            type: "POST",
            data: {
                date : date
            },
            success: function(arr) {
                $.ajax({
                    type: 'GET',
                    url: '/search/refresh01',
                    dataType: 'html',
                    success: function(data) {
                        $('#sample02').empty();
                        $('#sample02').append(data);
                        //window.scrollTo(0,document.body.scrollHeight);

                    },
                    error:function() {
                        alert('問題がありました。');
                    }
                });
            },
            error:function(arr) {
                alert('問題がありました。');
            }
        });
    }

    function TimePost2(date, clock1, clock2) {
        $('#sample01').addClass('sk-loading');

        $.ajax({
            url: "/search/time-post2",
            type: "POST",
            data: {
                date  : date,
                clock1 : clock1,
                clock2 : clock2
            },
            success: function(arr) {
                $.ajax({
                    type: 'GET',
                    url: '/search/refresh02',
                    dataType: 'html',
                    success: function(data) {
                        $('#sample01').empty();
                        $('#sample01').append(data);

                    },
                    error:function() {
                        alert('問題がありました。');
                        $('#sample01').removeClass('sk-loading');
                    },
                    complete:function() {
                        $('#sample01').removeClass('sk-loading');
                    }
                });

            },
            error:function(arr) {
                alert('問題がありました。');
            }
        });

    }

    function FinishPost(search, time, start_pos, date, clock1, clock2) {
        var ajaxpost = $.ajax({
            url: "/search/search",
            type: "POST",
            data: {
                search : search,
                time   : time,
                start_pos : start_pos,
                date   : date,
                clock1 : clock1,
                clock2 : clock2
            },
            success: function(arr) {
                //console.log(arr);
                if (arr == 0 || arr == -1 || arr == -2) {
                    $('#page-wrapper').removeClass('sk-loading');
                    swal({
                        title: "あなたが選択した条件では最適経路が見つかりませんでした",
                        text: "お手数ですが、条件を変更して再度検索してください",
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "OK",
                        closeOnConfirm: false
                    });
                    return false;
                }
                window.location.href = "/result";


            },
            error:function() {
                alert('問題がありました。');
            }
        });
        return ajaxpost;
    }

    function NoStep1(clock1, clock2) {
        var c = parseInt(clock1.substr(0,2)*60) + parseInt(clock1.substr(3,2));
        var d = parseInt(clock2.substr(0,2)*60 )+ parseInt(clock2.substr(3,2));
        if (parseInt(c) >= parseInt(d) || parseInt(c) >= 1080 || parseInt(c) < 540 || parseInt(d) <= 540 || parseInt(d) > 1080) {
            return false;
        } else {
            return true;
        }
    }
    function NoStep2(start_pos) {
        if (!start_pos) {
            $('#select-start-pos-error').removeClass('text-muted').addClass('text-danger').addClass('phone-display');
            return false;
        } else {
            //$('#select-start-pos-error').hide();
            return true;
        }
    }
    function FinishCheck() {
        var j = 0;
        var search = new Array();
        $('input[name="select-p"]:checked').map(function() {
            search[j] = $(this).val();
            j++;
        });
        return search;
    }
    function FinishTimeCheck(search) {
        var i;
        var N = search.length;
        var time = new Array();
        for (i=0; i<N; i++) {
            time[i] = $('select[name="time' + search[i] + '"]').val();
        }
        return time;

    }
    function ErrorMsg(title, text) {
        swal({
            title: title,
            text: text,
            type: "warning",
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "OK",
            closeOnConfirm: false
        });
    }
</script>

</body>

</html>

